### ISSUE TITLE
Android running problems

### ISSUE THREAD

**Issue by Nuclear6** [mbzuai-oryx/MobiLlama#9]
Great project! After I installed the apk on my Android device, I was able to run the 05B model and enter questions to get some feedback. 
![a65d897840b06038cc6689d5c68e66ef](https://github.com/mbzuai-oryx/MobiLlama/assets/49468241/80067713-101b-4d78-8671-f65ead393fd2)

But I have some questions:
1) The output content seems to be somewhat irrelevant to the problem;
2) Can the code for loading local models in apk be open source;
3) Whether the model supports fine-tuning so that it can handle specific business scenarios;

**Comment by OmkarThawakar** [comment]
Hi @Nuclear6 

Thanks for interest in our work. 

We have provided the quantized gguf model in app, which might degrade the quality of responses.

For full code of android APK please refer to llama.cpp (https://github.com/ggerganov/llama.cpp) and llama_cpp_dart (https://github.com/netdur/llama_cpp_dart).

Yes, our model supports finetuning, please use FastChat repo (https://github.com/lm-sys/FastChat) to finetune our model for specific business scenarios. 

Thanks,
